name: The Pipeline

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  contents: read

jobs:
  sca:
    name: "SCA: npm audit"
    runs-on: ubuntu-latest
    steps:
      - name: Get nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - parallel:
        - name: npm audit (server)
          run: npm audit --ignore-scripts
        - name: npm audit (frontend)
          run: npm audit --ignore-scripts
          working-directory: ./frontend

  sast:
    name: "SAST: semgrep"
    runs-on: ubuntu-latest
    steps:
      - name: Install semgrep
        run: pip install semgrep
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Semgrep scan
        run: semgrep --config auto --error --exclude 'data/static/codefixes/**' .

  secret-scanning:
    name: "Secret scanning: gitleaks"
    runs-on: ubuntu-latest
    steps:
      - name: Install gitleaks
        run: |
          curl -Lo /tmp/gitleaks.zip https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_linux_x64.tar.gz
          echo "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb /tmp/gitleaks.zip" | sha256sum -c -
          tar -C /tmp -xf /tmp/gitleaks.zip gitleaks
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: gitleaks scan
        run: /tmp/gitleaks dir -v --config .github/gitleaks.toml .

  build:
    name: "Build the container"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Remove encrypted and test files
        run: |
          rm data/static/users.yml encryptionkeys/jwt.priv
          find . -name '*.spec.ts' -delete
      - name: Build container
        run: docker build -t juice-shop .
      - name: Export image
        run: docker image save juice-shop | zstd > docker-image.tar.zst
      - name: Upload image artifact
        uses: actions/upload-artifact@v7
        id: upload
        with:
          name: docker-image
          path: docker-image.tar.zst
          if-no-files-found: error
          archive: false
    outputs:
      artifact: ${{ steps.upload.outputs.artifact-id }}

  dast:
    name: "DAST: nikto"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - parallel:
        - name: Download the docker image
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{ needs.build.outputs.artifact }}
            skip-decompress: true
        - name: Install git-crypt
          run: |
            curl -Lo /tmp/git-crypt https://github.com/AGWA/git-crypt/releases/download/0.8.0/git-crypt-0.8.0-linux-x86_64
            echo "522683f89693ad2da1f3fa7e1076f5e8934619a55ff2e1246866eeb2ad587b0c /tmp/git-crypt" | sha256sum -c -
            chmod +x /tmp/git-crypt
            sudo mv /tmp/git-crypt /usr/local/bin/git-crypt
            sudo chown root:root /usr/local/bin/git-crypt
        - name: Clone repository
          uses: actions/checkout@v6
          with:
            fetch-depth: 0
            path: source
        - name: Pre-fetch nikto docker container
          run: docker pull ghcr.io/sullo/nikto:latest
        - name: Create test network
          run: docker network create test-net
      - parallel:
        - name: Decrypt repository with git-crypt
          run: echo "$KEY" | base64 -d | git-crypt unlock /dev/stdin
          working-directory: source
          env:
            KEY: ${{ secrets.GIT_CRYPT_KEY }}
        - name: Import docker image
          run: docker image load -i docker-image.tar.zst
      - name: Start the juice-shop docker container
        run: |
          docker run \
            -dh juice-shop \
            --name juice-shop \
            --rm \
            --network test-net \
            -v $PWD/source/data/static/users.yml:/juice-shop/data/static/users.yml:ro \
            -v $PWD/source/encryptionkeys/jwt.priv:/juice-shop/encryptionkeys/jwt.priv:ro \
            juice-shop
      - name: Wait a while for it to initalize
        run: |
          sleep 30
          docker inspect juice-shop -f '{{ .State.Status }}' | grep '^running$'
      - name: Run nikto
        run: |
          mkdir output
          chmod 1777 output
          docker run \
            --rm \
            -h nikto \
            --name nikto \
            --network test-net \
            -v $PWD/output:/output \
            ghcr.io/sullo/nikto:latest \
            -h http://juice-shop:3000 \
            -o /output/nikto.json \
            -Tuning x567
      - name: Upload scan results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: nikto-results
          path: output/nikto.json
          if-no-files-found: error
          archive: false

  trivy:
    name: Scan docker image with trivy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - parallel:
        - name: Download trivy
          run: |
            curl -Lo trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v0.71.2/trivy_0.71.2_Linux-64bit.tar.gz
            echo "0510e71e2fd39bf863856d499c8dc19feb4e7336546394c502a8f5cc7ab27460 trivy.tar.gz" | sha256sum -c -
            tar -xf trivy.tar.gz
        - name: Download the docker image
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{ needs.build.outputs.artifact }}
            skip-decompress: true
      - name: Scan image with trivy
        run: |
          zstd -d docker-image.tar.zst
          ./trivy image --severity HIGH,CRITICAL juice-shop:latest --format json -o trivy.json --input docker-image.tar
      - name: Upload scan results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-results
          path: trivy.json
          if-no-files-found: error
          archive: false

  publish:
    name: Push image to ghcr.io
    runs-on: ubuntu-latest
    needs: [trivy, build, sca, sast, dast, secret-scanning]
    if: always() && needs.build.result == "success" && needs.trivy.result == "success"
    permissions:
      packages: write
    steps:
      - parallel:
        - name: Download the docker image
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{ needs.build.outputs.artifact }}
            skip-decompress: true
        - name: Authenticate with ghcr.io
          run: echo $GITHUB_TOKEN | docker login ghcr.io -u mini-bomba --password-stdin


