name: The Pipeline

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  artifact-metadata: write
  contents: read

jobs:
  sca:
    name: "SCA: npm audit"
    runs-on: ubuntu-latest
    steps:
      - name: Get nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - parallel:
        - name: npm audit (server)
          run: npm audit --ignore-scripts
        - name: npm audit (frontend)
          run: npm audit --ignore-scripts
          working-directory: ./frontend

  sast:
    name: "SAST: semgrep"
    runs-on: ubuntu-latest
    steps:
      - name: Install semgrep
        run: pip install semgrep
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Semgrep scan
        run: semgrep --config auto --error --exclude 'data/static/codefixes/**' .

  secret-scanning:
    name: "Secret scanning: gitleaks"
    runs-on: ubuntu-latest
    steps:
      - name: Install gitleaks
        run: |
          curl -Lo /tmp/gitleaks.zip https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_linux_x64.tar.gz
          echo "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb /tmp/gitleaks.zip" | sha256sum -c -
          tar -C /tmp -xf /tmp/gitleaks.zip gitleaks
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: gitleaks scan
        run: /tmp/gitleaks dir -v --config .github/gitleaks.toml .

  build:
    name: "Build the container"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Remove encrypted files
        run: rm data/static/users.yml encryptionkeys/jwt.priv
      - name: Build container
        run: docker build -t juice-shop .
      - name: Export image
        run: docker image save juice-shop | zstd > docker-image.tar.zst
      - name: Upload image artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-image
          path: docker-image.tar.zst
          if-no-files-found: error
          archive: false
