name: The Pipeline

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  artifact-metadata: write
  contents: read

jobs:
  sca:
    name: "SCA: npm audit"
    runs-on: ubuntu-latest
    steps:
      - name: Get nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: npm audit (server)
        run: npm audit --audit-level moderate --ignore-scripts
      - name: npm audit (frontend)
        run: npm audit --audit-level moderate --ignore-scripts
        working-directory: ./frontend
